name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
env:
  MY_VARIABLE: 'Hello, GitHub Actions!'
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "$MY_VARIABLE"
